language: node_js
node_js:
  - 10
yarn: true
cache:
  yarn: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

script:
  - yarn test && yarn travis-deploy-once "yarn semantic-release"

after_success:
  - echo "Preparing AWS Lambda Deploy"
  - yarn global add serverless
  - sls deploy
# deploy:
#   provider: script
#   script: ./scripts/deploy.sh
#   on:
#     # condition: $DEPLOY_BUILD = true
#     branch: master
