language: node_js
node_js:
- 'stable'

cache:
  directories:
    - node_modules

# after_success:
# - echo "Preparing AWS Lambda Deploy"
# - npm install -g serverless
# - sls deploy

deploy:
  provider: script
  script: ./scripts/deploy.sh
  on:
    # condition: $DEPLOY_BUILD = true
    branch: master
