language: node_js
node_js:
  - '8'
yarn: true
cache:
  directories:
    - node_modules

script:
  - yarn test && yarn travis-deploy-once "yarn semantic-release"

after_success:
  - echo "Preparing AWS Lambda Deploy"
  - yarn global add serverless
  - sls deploy
# deploy:
#   provider: script
#   script: ./scripts/deploy.sh
#   on:
#     # condition: $DEPLOY_BUILD = true
#     branch: master
