service:
  name: techcheck-server

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs6.10
  region: us-west-2

functions:
  get-script:
    handler: gen-script.default
    events:
      - http:
          method: get
          path: /preflight
